version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    volumes:
      - firefly_iii_db:/var/lib/mysql
    env_file: .db.env
volumes:
   firefly_iii_upload:
   firefly_iii_db:
